networks:
  dev:


services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8888"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - dev
